[project]
authors = ["Alex Kreidler <alex.contributing@alexkreidler.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "marker-server"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
fastapi = ">=0.115.6,<0.116"
python = "3.11.*"
numpy = ">=2.1.3,<3"
scipy = ">=1.14.1,<2"
pytorch = ">=2.5.1,<3"
uvicorn = ">=0.32.1,<0.33"

[pypi-dependencies]
marker-pdf = "*"
modal = "*"