[project]
authors = ["Alex Kreidler <alex.contributing@alexkreidler.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "marker-server"
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
numpy = ">=2.1.3,<3"
scipy = ">=1.14.1,<2"
pytorch = ">=2.5.1,<3"
pip = ">=24.3.1,<25"

[pypi-dependencies]
marker-pdf = "*"
beam-client = "*"
modal = ">=0.67.43, <0.68"
