
FROM nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04

WORKDIR /app

RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://pixi.sh/install.sh | bash

COPY . .

RUN pixi install

EXPOSE 8000

ENTRYPOINT "./docker/entrypoint.sh"

CMD ["uvicorn", "src.server:app", "--host", "0.0.0.0", "--port", "8000"]