name: Build Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push beam image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile.beam
          push: true
          tags: ghcr.io/${{ github.repository }}:1.0.2-beam
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push modal image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile.modal
          push: true
          tags: ghcr.io/${{ github.repository }}:1.0.2-modal
          cache-from: type=gha
          cache-to: type=gha,mode=max